### ISSUE TITLE
Issues running on Raspberry pi4

### ISSUE THREAD

**Issue by tonemking** [bmoers/docker-mid-server#12]
Getting stuck in a CrashLoopBackOff when trying to deploy with Kubernetes.

Here is my yaml file
```
apiVersion: apps/v1
kind: Deployment
metadata:
   name: mid-server-dev
   labels:
      app: mid-server-dev
spec:
   replicas: 1
   selector:
      matchLabels:
         app: mid-server-dev
   template:
      metadata:
         labels:
            app: mid-server-dev
      spec:
         containers:
         - name: mid-server
           image: moers/mid-server:madrid.latest
           env:
              - name: HOST
                value: midserverdev
              - name: USER_NAME
                value: miduser
              - name: PASSWORD
                value: 'midpass'
           imagePullPolicy: Always
```

Here are the events

Normal   Scheduled  9m59s                   default-scheduler  Successfully assigned default/mid-server-dev-767cf45b57-xdqwt to k8s-worker-02
  Normal   Pulled     8m52s                   kubelet            Successfully pulled image "moers/mid-server:paris.latest" in 1m6.391426568s
  Normal   Pulled     8m44s                   kubelet            Successfully pulled image "moers/mid-server:paris.latest" in 746.891844ms
  Normal   Pulled     8m26s                   kubelet            Successfully pulled image "moers/mid-server:paris.latest" in 1.016216712s
  Normal   Created    8m1s (x4 over 8m47s)    kubelet            Created container mid-server
  Normal   Started    8m1s (x4 over 8m46s)    kubelet            Started container mid-server
  Normal   Pulled     8m1s                    kubelet            Successfully pulled image "moers/mid-server:paris.latest" in 780.482185ms
  Normal   Pulling    7m10s (x5 over 9m58s)   kubelet            Pulling image "moers/mid-server:paris.latest"
  Warning  BackOff    4m52s (x19 over 8m43s)  kubelet            Back-off restarting failed container

Here is the processor architecture
Linux k8s-master 5.4.0-1023-raspi #26-Ubuntu SMP PREEMPT Thu Nov 12 14:58:33 UTC 2020 aarch64 aarch64 aarch64 GNU/Linux

Any suggestions on getting this to work on a Pi?
